apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: o79zkn4ri-go 
  janus-idp.io/tekton: o79zkn4ri-go
  backstage.io/kubernetes-id: o79zkn4ri-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: o79zkn4ri-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml